version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dragncards_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    image: elixir:1.14.4
    depends_on: 
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    entrypoint: /app/scripts/local-dev.sh
    working_dir: /app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dragncards_dev
    volumes:
      - ./frontend:/app
    entrypoint: /app/scripts/local-dev.sh
    working_dir: /app
    environment:
      - REACT_APP_BE_HOSTNAME=backend
#uncomment apache if you're running pure offline mode. Other steps required
#   apache:
#     image: httpd:latest
#     container_name: my-apache-app
#     ports:
#     - '8080:80'
#     volumes:
#     - ./images:/usr/local/apache2/htdocs
volumes:
  pgdata:
# images:
