services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    depends_on: 
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    entrypoint: /app/scripts/local-dev.sh
    working_dir: /app
    environment:
      - DB_HOSTNAME=postgres
  frontend:
    image: node:20
    depends_on: 
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    entrypoint: /app/scripts/local-dev.sh
    working_dir: /app
    environment:
      - REACT_APP_BE_HOSTNAME=backend
volumes:
  pgdata: